######################################################################
# 基础信息
######################################################################
base:
  login:
    alive-time: 1800 # 登录过期时间（单位：秒）


######################################################################
# 系统安全
######################################################################
security:
  secretKey: 'breezeSecret2020' #系统密钥
  secretAuthKey: 'breeze2020Secret'  #登录密码加密秘钥

######################################################################
# 数据库
######################################################################
database:
  default:
    # 连接驱动
    driverClassName: 'org.mariadb.jdbc.Driver'
    # 连接地址
    url: 'jdbc:mariadb://localhost:3306/breeze?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true'
    # 用户名
    username: 'root'
    # 密码
    password: 'vyr2aufREVmAqWB4HyH0gQ=='
    # 初始连接数
    initialSize: 5
    # 最大连接数
    maxActive: 20
    # 最小空闲
    minIdle: 5
    # 最长等待时间
    maxWait: 600000
    # 销毁线程检测连接间隔
    timeBetweenEvictionRunsMillis: 600000
    minEvictableIdleTimeMillis: 600000
    # 验证的SQL语句
    validationQuery: SELECT 1
    # 检测连接是否有效
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 是否缓存preparedStatement，也就是PSCache
    poolPreparedStatements: true
    # 要启用PSCache，必须配置大于0
    maxOpenPreparedStatements: 100
    # 每个PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
######################################################################
# 缓存Redis
######################################################################
redis:
  default:
    host: localhost
    port: 6379
    password: 'tmduND95v3S5Csr2gLJ9xw=='
    max_active: 1024 # 可用连接实例的最大数目，默认值为8；如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
    max_idle: 200 # 控制一个pool最多有多少个状态为idle(空闲的)的jedis实例，默认值也是8。
    max_wait: 10000 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException；
    timeout: 10000  # 超时时间

######################################################################
# 响应码
######################################################################
response:
  code:
    0: '请求成功'
    10001: '未知的请求地址'
    10002: '未经许可的请求方式'
    10003: '请求参数验证失败'
    20001: '用户名不存在'
    20002: '用户密码验证失败'
    20003: '用户已禁用'
    20004: '用户已锁定'
    20005: '用户未登录'
    20006: '验证码已过期'
    20007: '验证码错误'
    20008: '用户登录信息已过期'
    20009: '用户登录失败'
    40001: '权限不足'